version: '3'

services:
  website:
    restart: unless-stopped
    build:
      context: ./ag-web-typescript
      dockerfile: Dockerfile-website-dev
    container_name: ag-dev-website
    ports:
      - "4200:80"
    volumes:
      - ./ag-web-typescript/src:/usr/src/app/src
    command: ng serve

#   nginx:
#     image: nginx:latest
#     restart: unless-stopped
#     container_name: ag-dev-nginx
#     ports:
#       - "80:80"
#     volumes:
#       - ./ag-web-typescript/dist:/www/typescript
#       - ./nginx/development/conf.d:/etc/nginx/conf.d

  django:
    restart: unless-stopped
    build:
      context: ./autograder-server
      dockerfile: Dockerfile-django-dev
    container_name: ag-dev-django
    expose:
      - "8001"
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi.ini --python-autoreload 1
    env_file:
      - ./autograder-server/_dev.env

  postgres:
    restart: unless-stopped
    image: postgres:latest
    container_name: ag-dev-postgres
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    restart: unless-stopped
    image: redis:latest
    container_name: ag-dev-redis
    expose:
      - "6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: 127.0.0.1:5000/rabbitmq
    restart: unless-stopped
    image: rabbitmq:latest
    container_name: ag-dev-rabbitmq
    hostname: rabbit
    expose:
      - "5672"

  celery_small_tasks:
    restart: unless-stopped
    build:
      context: ./autograder-server
      dockerfile: Dockerfile-django-dev
    container_name: ag-dev-celery-small-tasks
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/celery worker -c 1 -A autograder -l info -Q small_tasks -n small_tasks@%h
    env_file:
      - ./autograder-server/_dev.env

  celery_project_downloads:
    restart: unless-stopped
    build:
      context: ./autograder-server
      dockerfile: Dockerfile-django-dev
    container_name: ag-dev-celery-project-downloads
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/celery worker -c 1 -A autograder -l info -Q project_downloads -n project_downloads@%h
    env_file:
      - ./autograder-server/_dev.env

  celerybeat:
    container_name: ag-dev-celerybeat
    restart: unless-stopped
    build:
      context: ./autograder-server
      dockerfile: Dockerfile-django-dev
    env_file:
      - ./autograder-server/_dev.env
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/celery worker --beat -c 1 -A autograder -l info -Q periodic_tasks -n periodic_tasks@%h

   # environment:
   #  AG_SUBMISSION_LISTENER_INTERVAL: 5

  grader:
    container_name: ag-dev-grader
    build:
      dockerfile: Dockerfile-grader-dev
      context: ./autograder-server

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autograder-server:/usr/src/app

    env_file:
      - ./autograder-server/_dev.env

    command: /usr/local/bin/celery -A autograder worker -n submission_grader@%h --loglevel=info -c 1

  deferred_grader:
    container_name: ag-dev-deferred-grader
    build:
      dockerfile: Dockerfile-grader-dev
      context: ./autograder-server

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autograder-server:/usr/src/app
    env_file:
      - ./autograder-server/_dev.env

    command: /usr/local/bin/celery -A autograder worker -Q deferred,rerun -n deferred@%h --loglevel=info -c 1

volumes:
  redisdata: {}
  pgdata: {}
