version: '2'

services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    container_name: ag-dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./ag-web-typescript/dist:/www/typescript
      - ./nginx/development/conf.d:/etc/nginx/conf.d

  django:
    extends:
      file: docker-compose.yml
      service: django
    container_name: ag-dev-django
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi.ini --python-autoreload 1
    env_file:
      - ./autograder-server/_dev.env

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    container_name: ag-dev-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    container_name: ag-dev-redis

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    container_name: ag-dev-rabbitmq

  celerybeat:
    extends:
      file: docker-compose.yml
      service: celerybeat
    container_name: ag-dev-celerybeat
    env_file:
      - ./autograder-server/_dev.env
#    environment:
    #   AG_SUBMISSION_LISTENER_INTERVAL: 60

  celery_small_tasks:
    extends:
      file: docker-compose.yml
      service: celery_small_tasks
    container_name: ag-dev-celery-small-tasks
    env_file:
      - ./autograder-server/_dev.env

  grader:
    extends:
      file: docker-compose.yml
      service: grader
    container_name: ag-dev-grader
    env_file:
      - ./autograder-server/_dev.env
    environment:
      AG_REDIS_HOST: 'redis'  # In dev, grader nodes can share the redis server

  deferred_grader:
    extends:
      file: docker-compose.yml
      service: deferred_grader
    container_name: ag-dev-deferred-grader
    env_file:
      - ./autograder-server/_dev.env
    environment:
      AG_REDIS_HOST: 'redis'  # In dev, grader nodes can share the redis server

volumes:
  redisdata: {}
  pgdata: {}
