version: '2'

services:
  nginx:
    build: ./nginx/production
    restart: unless-stopped
    container_name: ag-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ag-web-typescript/dist:/www/typescript
      - /etc/ssl:/etc/ssl
      - ./nginx/production/conf.d:/etc/nginx/conf.d

  django:
    image: 127.0.0.1:5000/django
    restart: unless-stopped
    build: ./autograder-server
    container_name: ag-django
    expose:
      - "8001"
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi.ini
    env_file:
      - ./autograder-server/_prod.env

  postgres:
    image: 127.0.0.1:5000/postgres
    restart: unless-stopped
    image: postgres:latest
    container_name: ag-postgres
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres' # UPDATE THIS

  # http://redis.io/topics/security
  redis:
    image: 127.0.0.1:5000/redis
    restart: unless-stopped
    image: redis:latest
    container_name: ag-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redisdata:/data

  rabbitmq:
    image: 127.0.0.1:5000/rabbitmq
    restart: unless-stopped
    image: rabbitmq:latest
    container_name: ag-rabbitmq
    hostname: rabbit
    ports:
      - "127.0.0.1:5672:5672"

  celery_small_tasks:
    image: 127.0.0.1:5000/celery_small_tasks
    extends:
      service: django
    command: /usr/local/bin/celery worker -c 4 -A autograder -l info -Q small_tasks -n small_tasks@%h
    container_name: ag-celery-small-tasks

  celerybeat:
    image: 127.0.0.1:5000/celerybeat
    extends:
      service: django
    command: /usr/local/bin/celery worker --beat -c 1 -A autograder -l info -Q periodic_tasks -n periodic_tasks@%h
    container_name: ag-celerybeat

    # environment:
        # AG_SUBMISSION_LISTENER_INTERVAL:

  grader:
    container_name: ag-grader
    build:
      dockerfile: Dockerfile-grader
      context: ./autograder-server
    image: 127.0.0.1:5000/grader
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./autograder-server:/usr/src/app
    env_file:
      - ./autograder-server/_prod.env
    environment:
      AG_REDIS_HOST: 'localhost'  # grader nodes should all have their own redis server

    command: /usr/local/bin/celery -A autograder worker -n submission_grader@%h --loglevel=info -c 1

  deferred_grader:
    container_name: ag-deferred-grader
    extends:
      service: grader
    command: /usr/local/bin/celery -A autograder worker -Q deferred -n deferred@%h --loglevel=info -c 1

volumes:
  redisdata: {}
  pgdata: {}
