version: '2'

services:
  nginx:
    restart: always
    build: ./nginx/development
    container_name: ag-dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./ag-web-typescript:/www/static

  django:
    extends:
      file: docker-compose.yml
      service: django
    container_name: ag-dev-django
    expose:
      - "8001"
    environment:
      DJANGO_SETTINGS_MODULE: 'autograder.settings.development'
      ALLOWED_HOSTS: '*'
      # Set to 'false' to disable real authentication. Any other string value
      # will enable real authentication
      USE_REAL_AUTH: 'true'

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    container_name: ag-dev-postgres

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    container_name: ag-dev-redis

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq

  celerybeat:
    extends:
      file: docker-compose.yml
      service: celerybeat

    environment:
      AG_DEFERRED_CHECKER_INTERVAL: '5'


volumes:
  redisdata: {}
  pgdata: {}
