version: '2'

services:
  # js:
  #   restart: always
  #   build: ./ag-web-typescript
  #   container_name: ag-dev-js
  #   ports:
  #     - 3000:3000
  #     - 3001:3001
  #   volumes:
  #       - ./ag-web-typescript:/quickstart

  nginx:
    restart: always
    build: ./nginx/development
    container_name: ag-dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./ag-web-typescript:/www/static

  django:
    restart: always
    build: ./autograder-server
    container_name: ag-dev-django
    expose:
      - "8001"
    volumes:
      - ./autograder-server:/usr/src/app
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi-dev.ini
    environment:
      AG_DB_NAME: 'postgres'
      AG_DB_HOST: 'postgres'
      AG_DB_USER: 'postgres'
      AG_DB_PASSWORD: 'postgres' # UPDATE THIS
      AG_REDIS_HOST: 'redis'

  postgres:
    restart: always
    image: postgres:latest
    container_name: ag-dev-postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres' # UPDATE THIS

  # http://redis.io/topics/security
  redis:
    restart: always
    image: redis:latest
    container_name: ag-dev-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  web: {}
  redisdata: {}
  pgdata: {}
