version: '2'

services:
  nginx:
    restart: always
    build: ./nginx/development
    container_name: ag-dev-nginx
    ports:
      - "80:80"
    volumes:
      - ./ag-web-typescript/dist:/www/typescript

  django:
    extends:
      file: docker-compose.yml
      service: django
    container_name: ag-dev-django
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi.ini --python-autoreload 1

    environment:
      DJANGO_SETTINGS_MODULE: 'autograder.settings.development'
      ALLOWED_HOSTS: '*'
      OAUTH2_SECRETS_FILENAME: 'dev_oauth2_secrets.json'
        # Set to false to disable real authentication. Any other string value
        # will enable real authentication.
        # Then, using a browser plugin such as EditThisCookie, set the
      # cookie "username: '<email>" to set which user you want to'
        # authenticate as.
      USE_REAL_AUTH: 'false'
      AG_DB_PASSWORD: 'postgres'

      AG_DB_HOST: 'postgres'
      AG_REDIS_HOST: 'redis'

      AG_CELERY_BROKER_URL: 'amqp://guest@rabbitmq:5672//'
      AG_CELERY_RESULTS_BACKEND_URL: 'redis://redis:6379/0'

#    env_file:
#      - ./autograder-server/_dev.env

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres
    container_name: ag-dev-postgres
    environment:
      POSTGRES_PASSWORD: 'postgres'

  redis:
    extends:
      file: docker-compose.yml
      service: redis
    container_name: ag-dev-redis

  rabbitmq:
    extends:
      file: docker-compose.yml
      service: rabbitmq
    container_name: ag-dev-rabbitmq

  celerybeat:
    extends:
      file: docker-compose.yml
      service: celerybeat
    container_name: ag-dev-celerybeat

    environment:
      DJANGO_SETTINGS_MODULE: 'autograder.settings.development'
      AG_DB_PASSWORD: 'postgres'

      AG_DB_HOST: 'postgres'
      AG_REDIS_HOST: 'redis'

      AG_CELERY_BROKER_URL: 'amqp://guest@rabbitmq:5672//'
      AG_CELERY_RESULTS_BACKEND_URL: 'redis://redis:6379/0'
#    env_file:
#      - ./autograder-server/_dev.env

    #   AG_SUBMISSION_LISTENER_INTERVAL: 60

  celery_small_tasks:
    extends:
      file: docker-compose.yml
      service: celery_small_tasks
    container_name: ag-dev-celery-small-tasks

    environment:
      DJANGO_SETTINGS_MODULE: 'autograder.settings.development'
      AG_DB_PASSWORD: 'postgres'

      AG_DB_HOST: 'postgres'
      AG_REDIS_HOST: 'redis'

      AG_CELERY_BROKER_URL: 'amqp://guest@rabbitmq:5672//'
      AG_CELERY_RESULTS_BACKEND_URL: 'redis://redis:6379/0'
#    env_file:
#      - ./autograder-server/_dev.env

  grader:
    extends:
      file: docker-compose.yml
      service: grader

    container_name: ag-dev-grader

    environment:
      DJANGO_SETTINGS_MODULE: 'autograder.settings.development'
#      ALLOWED_HOSTS: '*'
#      OAUTH2_SECRETS_FILENAME: 'dev_oauth2_secrets.json'
        # Set to false to disable real authentication. Any other string value
        # will enable real authentication.
        # Then, using a browser plugin such as EditThisCookie, set the
      # cookie "username: '<email>" to set which user you want to'
        # authenticate as.
#      USE_REAL_AUTH: 'false'
      AG_DB_PASSWORD: 'postgres'

      AG_DB_HOST: 'postgres'
      AG_REDIS_HOST: 'redis'

      AG_CELERY_BROKER_URL: 'amqp://guest@rabbitmq:5672//'
      AG_CELERY_RESULTS_BACKEND_URL: 'redis://redis:6379/0'

#    env_file:
#      - ./autograder-server/_dev.env


volumes:
  redisdata: {}
  pgdata: {}
