version: '2'

services:
  nginx:
    restart: always
    build: ./nginx/production
    container_name: ag-nginx
    ports:
      - "80:80"
    volumes:
      - ./autograder-web-interface/web_autograder/build_dev/web:/www/static
    # environment:
    #    ssl_certificate
    #    ssl_certificate_key

  django:
    restart: always
    build: ./autograder-server
    container_name: ag-django
    expose:
      - "8001"
    volumes:
      - ./autograder-server:/usr/src/app
      - ../media_root:/usr/src/media_root
    command: /usr/local/bin/uwsgi --ini /usr/src/app/uwsgi/uwsgi-dev.ini
    environment:
      MEDIA_ROOT: /usr/src/media_root

      AG_DB_NAME: 'postgres'
      AG_DB_USER: 'postgres'
      AG_DB_PASSWORD: 'postgres' # UPDATE THIS
      AG_DB_HOST: 'postgres'
      AG_DB_PORT: '5432'

      AG_REDIS_HOST: 'redis'
      AG_REDIS_PORT: '6379'


  postgres:
    restart: always
    image: postgres:latest
    container_name: ag-postgres
    ports:
      - "localhost:5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: 'postgres' # UPDATE THIS

  # http://redis.io/topics/security
  redis:
    restart: always
    image: redis:latest
    container_name: ag-dev-redis
    ports:
      - "localhost:6379:6379"
    volumes:
      - redisdata:/data

volumes:
  redisdata: {}
  pgdata: {}
